-- Run this in Supabase: SQL Editor > New query.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  role text not null check (role in ('driver', 'admin')),
  password text not null
);

create table if not exists public.routes (
  id bigint generated by default as identity primary key,
  route_code text not null unique,
  zone text not null,
  driver_name text not null,
  finalized boolean not null default false,
  finalized_at timestamptz
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique,
  route_id bigint not null references public.routes(id) on delete cascade,
  customer text not null,
  address text not null,
  status text not null default 'Pendiente' check (status in ('Pendiente', 'Completa', 'Parcial')),
  notes text not null default '',
  updated_at timestamptz not null default now()
);

-- Demo data. Change the passwords before any real deployment.
insert into public.users (email, name, role, password) values
  ('chofer@rutalog.ar', 'Martín Pérez', 'driver', '123456'),
  ('admin@rutalog.ar', 'Ana Gómez', 'admin', '123456')
on conflict (email) do nothing;

insert into public.routes (route_code, zone, driver_name)
values ('R-284', 'Zona Centro', 'Martín Pérez')
on conflict (route_code) do nothing;

insert into public.orders (order_code, route_id, customer, address) values
  ('PED-1042', (select id from public.routes where route_code = 'R-284'), 'Almacén San Martín', 'Av. San Martín 1280'),
  ('PED-1043', (select id from public.routes where route_code = 'R-284'), 'Kiosco La Esquina', 'Belgrano 842'),
  ('PED-1044', (select id from public.routes where route_code = 'R-284'), 'Mercado Central', 'Rivadavia 220'),
  ('PED-1045', (select id from public.routes where route_code = 'R-284'), 'Autoservicio Norte', 'Mitre 1564')
on conflict (order_code) do nothing;
