const seedOrders = [
  { id:'PED-1042', customer:'Almacén San Martín', address:'Av. San Martín 1280', items:[['Bebida isotónica 500ml',12],['Agua mineral 1.5L',8]], status:'Pendiente' },
  { id:'PED-1043', customer:'Kiosco La Esquina', address:'Belgrano 842', items:[['Gaseosa cola 2.25L',6],['Jugo naranja 1L',10]], status:'Pendiente' },
  { id:'PED-1044', customer:'Mercado Central', address:'Rivadavia 220', items:[['Agua mineral 500ml',24],['Energizante 473ml',12]], status:'Pendiente' },
  { id:'PED-1045', customer:'Autoservicio Norte', address:'Mitre 1564', items:[['Gaseosa lima-limón 2.25L',6],['Tónica 1.5L',8]], status:'Pendiente' }
];
const app = document.querySelector('#app');
let state = JSON.parse(localStorage.getItem('rutalog-state')) || { user:null, orders:seedOrders, view:'home', active:null, choice:'Completa' };
const save = () => localStorage.setItem('rutalog-state', JSON.stringify(state));
async function api(path, options = {}) {
  const response = await fetch(path, { ...options, headers: { 'Content-Type':'application/json', ...(state.user ? {Authorization:`Bearer ${state.user.jwt}`} : {}), ...(options.headers || {}) } });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || 'No se pudo completar la operación');
  return data;
}
const initials = n => n.split(' ').map(x=>x[0]).slice(0,2).join('');
function header() { return `<header class="topbar"><div class="brand"><span class="brand-mark">↗</span>RutaLog</div><span class="avatar">${initials(state.user.name)}</span></header>`; }
function nav(active) { return `<nav class="nav"><button class="${active==='home'?'active':''}" onclick="go('home')"><i>⌂</i>Ruta</button><button class="${active==='orders'?'active':''}" onclick="go('orders')"><i>▤</i>Pedidos</button><button class="logout" onclick="logout()"><i>↪</i>Salir</button></nav>`; }
function progress() { return Math.round(state.orders.filter(o=>o.status!=='Pendiente').length / state.orders.length * 100); }
function badge(s) { const c=s==='Pendiente'?'pending':s==='Completa'?'done':'partial'; return `<span class="badge ${c}">${s}</span>`; }
function home() { const p=progress(); app.innerHTML = `${header()}<section class="content"><div class="welcome"><span class="eyebrow">Jornada en curso</span><h1>Hola, ${state.user.name.split(' ')[0]}</h1><p>Martes, 28 de julio · 08:30 h</p></div><article class="route-card"><small>RUTA ASIGNADA · R-284</small><h2>Zona Centro</h2><div class="route-meta"><span>◉ 4 paradas</span><span>◷ Finaliza 13:00</span></div><div class="progress"><b style="width:${p}%"></b></div><footer><span>${state.orders.filter(o=>o.status!=='Pendiente').length} de ${state.orders.length} pedidos gestionados</span><span>${p}%</span></footer></article><div class="section-title"><h2>Próximas entregas</h2><span>${state.orders.filter(o=>o.status==='Pendiente').length} pendientes</span></div>${state.orders.map(orderCard).join('')}</section>${nav('home')}`; }
function orderCard(o) { return `<article class="order"><div class="order-head"><div><h3>${o.customer}</h3><p>${o.address}</p></div>${badge(o.status)}</div><div class="order-foot"><span class="items">${o.items.length} productos · ${o.id}</span><button class="link-btn" onclick="openOrder('${o.id}')">${o.status==='Pendiente'?'Gestionar':'Ver detalle'} →</button></div></article>`; }
function orders() { app.innerHTML = `${header()}<section class="content"><div class="welcome"><span class="eyebrow">Ruta R-284</span><h1>Pedidos asignados</h1><p>Actualizá cada entrega durante el recorrido.</p></div><div class="section-title"><h2>${state.orders.length} paradas</h2><span>${progress()}% completo</span></div>${state.orders.map(orderCard).join('')}<button class="finalize" onclick="finishRoute()">Finalizar y enviar ruta</button></section>${nav('orders')}`; }
function detail() { const o=state.orders.find(x=>x.id===state.active); app.innerHTML = `${header()}<section class="content"><div class="detail-head"><button class="back" onclick="go('orders')">‹</button><h1>Registrar entrega</h1></div><article class="detail-card"><h2>${o.customer}</h2><p>${o.address}</p><p class="order-code">${o.id}</p><div class="item-list">${o.items.map(i=>`<div class="item-row"><span>${i[0]}<small>Unidades solicitadas</small></span><span class="qty">${i[1]} u.</span></div>`).join('')}</div></article><h2 class="action-title">Resultado de la entrega</h2><div class="action-grid"><button class="action complete ${state.choice==='Completa'?'selected':''}" onclick="selectChoice('Completa')">✓ Entrega completa</button><button class="action part ${state.choice==='Parcial'?'selected':''}" onclick="selectChoice('Parcial')">◐ Entrega parcial</button></div><h2 class="action-title">Observaciones <span style="font:400 12px DM Sans;color:#667572">(opcional)</span></h2><textarea id="notes" class="notes" placeholder="Ej. Se entregaron 8 unidades, faltan 2 por falta de stock.">${o.notes||''}</textarea><button class="primary submit" onclick="saveDelivery()">Confirmar registro</button></section>`; }
function admin() { const completed=state.orders.filter(o=>o.status==='Completa').length, partial=state.orders.filter(o=>o.status==='Parcial').length; app.innerHTML = `${header()}<section class="content"><div class="welcome"><span class="eyebrow">Administración</span><h1>Operación de hoy</h1><p>Seguimiento de rutas y entregas en tiempo real.</p></div><div class="admin-summary"><div class="stat"><strong>1</strong><span>rutas activas</span></div><div class="stat"><strong>${completed}</strong><span>completas</span></div><div class="stat"><strong>${partial}</strong><span>parciales</span></div></div><div class="section-title"><h2>Ruta R-284</h2><span>En curso</span></div>${state.orders.map(o=>`<article class="admin-route"><h3>${o.id} · ${o.customer}</h3><p>${o.address}${o.notes?` · ${o.notes}`:''}</p><footer><span>Chofer: Martín Pérez</span>${badge(o.status)}</footer></article>`).join('')}</section>${nav('home')}`; }
function login() { app.innerHTML = `<section class="login"><div class="brand"><span class="brand-mark">↗</span>RutaLog</div><div class="login-copy"><span class="eyebrow">Operación logística</span><h1>Tu ruta, siempre bajo control.</h1><p>Ingresá para consultar y gestionar las entregas de tu jornada.</p></div><form class="login-card" onsubmit="signIn(event)"><label class="field">Correo electrónico<input id="email" type="email" value="chofer@rutalog.ar" required /></label><label class="field">Contraseña<input type="password" value="123456" required /></label><button class="primary">Ingresar a mi cuenta</button><p class="demo-note"><strong>Demo:</strong> usá <strong>chofer@rutalog.ar</strong> para la vista de ruta o <strong>admin@rutalog.ar</strong> para administración.</p></form></section>`; }
async function signIn(e) { e.preventDefault(); const email=document.querySelector('#email').value.toLowerCase(); const password=document.querySelector('input[type=password]').value; const button=e.target.querySelector('button'); button.textContent='Ingresando...'; button.disabled=true; try { const session=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password})}); state.user={...session.user,jwt:session.token}; if(session.user.role==='driver') { const route=await api('/api/routes/current'); state.orders=route.orders; } else { const operations=await api('/api/admin/operations'); state.orders=operations.routes[0].orders; } state.view=session.user.role==='admin'?'admin':'home'; save(); render(); } catch(error) { toast(error.message); button.textContent='Ingresar a mi cuenta'; button.disabled=false; } }
function go(v) { state.view=v; save(); render(); } function openOrder(id) { state.active=id; state.choice=state.orders.find(o=>o.id===id).status==='Pendiente'?'Completa':state.orders.find(o=>o.id===id).status; state.view='detail'; render(); } function selectChoice(v) { state.choice=v; render(); }
async function saveDelivery() { const o=state.orders.find(x=>x.id===state.active); const notes=document.querySelector('#notes').value.trim(); try { const updated=await api(`/api/orders/${o.id}`,{method:'PUT',body:JSON.stringify({status:state.choice,notes})}); Object.assign(o,updated); save(); toast(`Pedido ${o.id} registrado como entrega ${state.choice.toLowerCase()}.`); go('orders'); } catch(error) { toast(error.message); } }
async function finishRoute() { if(state.orders.some(o=>o.status==='Pendiente')) return toast('Aún hay pedidos pendientes por registrar.'); try { await api('/api/routes/current/finalize',{method:'POST'}); state.routeSent=true; save(); toast('Ruta finalizada. La información fue enviada a administración.'); } catch(error) { toast(error.message); } }
function logout() { state.user=null; state.view='login'; save(); render(); } function toast(msg) { const t=document.createElement('div'); t.className='toast'; t.textContent=msg; document.body.append(t); setTimeout(()=>t.remove(),2600); }
function render() { if(!state.user) return login(); if(state.user.role==='admin') return admin(); if(state.view==='detail') return detail(); state.view==='orders'?orders():home(); } render();
